### ISSUE TITLE
Malformed path when loading smpl.* for tfmx music.

### ISSUE THREAD

**Issue by vtlmks** [mvtiaine/audacious-uade#16]
When opening TFMX songs it seems that the path is malformed when trying to load the smpl.* file

If the path is: /data/_computer_music/modland/TFMX/Chris Huelsbeck
it tries to load the smpl.* file from: /data/_computer_music/modland/TFMX/Chris Huelsbecksmpl.*
without the / at the end of the path.

**Comment by mvtiaine** [comment]
Which version are you using ?
The multifile support was indeed broken in 0.9.2-0.9.3 but should be fixed since 0.10.0 (and current master).

**Comment by vtlmks** [comment]
I see, my fault, I used the old PKGBUILD, I thought it automatically took the master, but I see now that it took 0.9.2, with master it works correctly! Thanks

**Comment by mvtiaine** [comment]
I've also noticed that Github sometimes serves stale data for quite some time with raw.gihubusercontent.com links, not sure if that could've been the issue.

Thanks for the report anyway, glad it's fixed now!
